Auth
lfryemason/strateachy pull request #2
Opened 2019-01-27 20:50 UTC by lfryemason

Finished the tutorial that creates a basic site design with authentication functionality.

2019-01-27 22:28 UTC, Vynlar requested changes

2019-01-27 22:28 UTC, Vynlar commented on src/components/Session/withAuthorization.js
> +const AuthCondition = authUser => !!authUser;
Generally function names are not capitalized. In react it's typical to only capitalize component names.

2019-01-27 22:28 UTC, Vynlar commented on src/components/PasswordChange/index.js
> +      .doPasswordUpdate(passwordOne)
Having a component directly call Firebase somehow feels dirty to me but I'm not sure what else you would do with your current setup. I bet it'll be fine for this scale of app but note that for larger applications this can get pretty painful to maintain.

2019-01-27 22:28 UTC, Vynlar commented on src/components/PasswordChange/index.js
> +        this.setState({ ...INITIAL_STATE });
I believe you can just directly pass in the `INITIAL_STATE` instead of making a copy of it?

2019-01-27 22:28 UTC, Vynlar commented on src/components/PasswordChange/index.js
> +        this.setState({ ...INITIAL_STATE });
Not a biggie though

2019-01-27 22:28 UTC, Vynlar commented on src/components/Session/withAuthorization.js
> +export { AuthCondition };
You can directly export in the definition of AuthCondition above:
```
export const AuthCondition = ...
```

2019-01-27 22:28 UTC, Vynlar commented on src/components/Session/withAuthorization.js
> +      this.listener = this.props.firebase.auth.onAuthStateChanged(
I would rename this to `this.removeListener` since that is what it is

2019-01-27 22:28 UTC, Vynlar commented on src/components/Session/withAuthorization.js
> +      this.listener();
And therefore update this to reflect that

2019-01-27 23:50 UTC, lfryemason commented on src/components/Session/withAuthorization.js
> +const AuthCondition = authUser => !!authUser;
Fixed

2019-01-28 00:23 UTC, lfryemason commented on src/components/PasswordChange/index.js
> +      .doPasswordUpdate(passwordOne)
Moved out of components folder

2019-01-28 00:31 UTC, lfryemason commented on src/components/Session/withAuthorization.js
> +export { AuthCondition };
Fixed

2019-01-28 00:33 UTC, lfryemason commented on src/components/Session/withAuthorization.js
> +      this.listener = this.props.firebase.auth.onAuthStateChanged(
Fixed

2019-01-28 00:35 UTC, merged